from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from database import db
from bson import ObjectId
from core.deps import get_current_user
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.pdfgen import canvas as pdf_canvas
import io
import re
from datetime import datetime, timezone

router = APIRouter(prefix="/api/v1/process", tags=["Report"])

PAGE_W = A4[0]
CONTENT_W = PAGE_W - 1.3 * inch  # left + right margins

BLUE = colors.HexColor("#1F3864")
LBLUE = colors.HexColor("#2E75B6")
GREY_BG = colors.HexColor("#F2F2F2")


def _esc(text) -> str:
    if text is None:
        return ""
    s = str(text).strip()
    s = s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    s = re.sub(r"[\r\n\t]+", " ", s)
    return s or "—"


def _money(val, currency: str = "INR") -> str:
    try:
        n = int(float(val or 0))
        if n == 0:
            return "—"
        return f"{currency} {n:,}"
    except (TypeError, ValueError):
        return "—"


def _num(val, suffix: str = "") -> str:
    try:
        v = float(val or 0)
        if v == 0:
            return "—"
        text = str(int(v)) if v == int(v) else f"{v:.1f}"
        return f"{text} {suffix}".strip() if suffix else text
    except (TypeError, ValueError):
        return "—"


def _float(val, default: float = 0.0) -> float:
    try:
        return float(val if val not in (None, "") else default)
    except (TypeError, ValueError):
        return default


ERROR_REDUCTION_PCT = 30
REVENUE_RECOVERY_PCT = 50


def _payback_metrics(step3: dict, step5: dict, payback: dict | None) -> dict:
    """Use saved step7 payback when present; otherwise derive from prior steps."""
    pb = payback or {}
    impl = _float(pb.get("implementation_cost"))

    if pb.get("annual_benefit") is not None and pb.get("payback_period_months") is not None:
        return {
            "implementation_cost": impl,
            "annual_benefit": _float(pb.get("annual_benefit")),
            "payback_period_months": pb.get("payback_period_months"),
        }

    automation_pct = _float(step5.get("automation_pct")) / 100
    annual_benefit = (
        _float(step3.get("fte_cost_annual")) * automation_pct
        + _float(step3.get("business_impact_errors_monthly")) * 12 * (ERROR_REDUCTION_PCT / 100)
        + _float(step3.get("revenue_leakage")) * (REVENUE_RECOVERY_PCT / 100)
    )
    monthly_benefit = annual_benefit / 12 if annual_benefit else 0
    payback_months = (
        round(impl / monthly_benefit, 1) if impl > 0 and monthly_benefit > 0 else None
    )
    return {
        "implementation_cost": impl,
        "annual_benefit": round(annual_benefit),
        "payback_period_months": payback_months,
    }


def _styles():
    return {
        "title": ParagraphStyle(
            "title", fontSize=18, textColor=BLUE, fontName="Helvetica-Bold",
            alignment=TA_CENTER, spaceAfter=4, leading=22,
        ),
        "sub": ParagraphStyle(
            "sub", fontSize=10, textColor=colors.grey,
            alignment=TA_CENTER, spaceAfter=14, leading=13,
        ),
        "section": ParagraphStyle(
            "section", fontSize=11, textColor=BLUE, fontName="Helvetica-Bold",
            spaceBefore=12, spaceAfter=6, leading=14,
        ),
        "body": ParagraphStyle(
            "body", fontSize=9, textColor=colors.black,
            leading=12, spaceAfter=4, wordWrap="CJK",
        ),
        "th": ParagraphStyle(
            "th", fontSize=9, fontName="Helvetica-Bold", textColor=colors.white,
            leading=11, wordWrap="CJK",
        ),
        "td": ParagraphStyle(
            "td", fontSize=8, fontName="Helvetica", textColor=colors.black,
            leading=10, wordWrap="CJK",
        ),
        "td_bold": ParagraphStyle(
            "td_bold", fontSize=8, fontName="Helvetica-Bold", textColor=BLUE,
            leading=10, wordWrap="CJK",
        ),
    }


def _para(text, style):
    return Paragraph(_esc(text), style)


def _row_paras(cells, styles_map, row_idx: int, header: bool = False):
    out = []
    for col_idx, cell in enumerate(cells):
        if header:
            st = styles_map["th"]
        elif col_idx == 0 and not header:
            st = styles_map["td_bold"]
        else:
            st = styles_map["td"]
        out.append(Paragraph(_esc(str(cell)), st))
    return out


def _footer_stamp() -> str:
    return f"Generated by AuRA — SenzCraft · {datetime.now(timezone.utc).strftime('%d %b %Y %H:%M UTC')}"


class _NumberedCanvas(pdf_canvas.Canvas):
    """Page number and footer stamp on every page."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict] = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.setFont("Helvetica", 8)
            self.setFillColor(colors.grey)
            self.drawCentredString(PAGE_W / 2, 0.7 * inch, _footer_stamp())
            self.setFont("Helvetica", 9)
            self.drawCentredString(PAGE_W / 2, 0.45 * inch, str(self._pageNumber))
            pdf_canvas.Canvas.showPage(self)
        pdf_canvas.Canvas.save(self)


def _make_table(rows, col_widths, header_blue: bool = True):
    """Build a table where every cell is a Paragraph (proper wrap)."""
    st = _styles()
    data = []
    for i, row in enumerate(rows):
        data.append(_row_paras(row, st, i, header=(i == 0 and header_blue)))

    table = Table(data, colWidths=col_widths, repeatRows=1 if header_blue else 0)
    cmds = [
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
    ]
    if header_blue:
        cmds += [
            ("BACKGROUND", (0, 0), (-1, 0), LBLUE),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, GREY_BG]),
        ]
    else:
        cmds += [
            ("BACKGROUND", (0, 0), (0, -1), GREY_BG),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, GREY_BG]),
        ]
    table.setStyle(TableStyle(cmds))
    return table


@router.get("/{process_id}/export-pdf")
async def export_pdf(process_id: str, user: dict = Depends(get_current_user)):
    p = await db.processes.find_one({"_id": ObjectId(process_id)})
    if not p:
        raise HTTPException(404, "Process not found")

    step1 = p.get("steps_data", {}).get("step1", {}) or {}
    step2 = p.get("steps_data", {}).get("step2", {}) or {}
    step3 = p.get("steps_data", {}).get("step3", {}) or {}
    step4 = p.get("steps_data", {}).get("step4", {}) or {}
    step5 = p.get("steps_data", {}).get("step5", {}) or {}
    step6 = p.get("steps_data", {}).get("step6", {}) or {}
    step7 = p.get("steps_data", {}).get("step7", {}) or {}
    report_fields = step7.get("report_fields", {}) or {}

    currency = step1.get("currency", "INR") or "INR"

    selected_archetypes = []
    if step6.get("archetypes"):
        selected_archetypes = [a for a in step6["archetypes"] if a.get("is_selected")]

    overall_gsda = 0
    if step5:
        overall_gsda = round((
            step5.get("standardization", 0) +
            step5.get("digitization", 0) +
            step5.get("data_availability", 0) +
            step5.get("automation_feasibility", 0)
        ) / 4, 1)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=0.65 * inch,
        leftMargin=0.65 * inch,
        topMargin=0.65 * inch,
        bottomMargin=0.65 * inch,
    )
    st = _styles()
    story = []

    # ── Cover ─────────────────────────────────────────────────────────────────
    story.append(Paragraph("AuRA — AI Discovery Platform", st["title"]))
    story.append(Paragraph("Process Discovery Assessment Report", st["sub"]))
    story.append(HRFlowable(width="100%", thickness=2, color=LBLUE))
    story.append(Spacer(1, 8))

    process_title = (
        step2.get("process_name")
        or report_fields.get("sub_process_name")
        or "Process Assessment"
    )
    story.append(_para(process_title, ParagraphStyle(
        "pt", fontSize=13, textColor=BLUE, fontName="Helvetica-Bold",
        spaceAfter=8, leading=16,
    )))

    # ── 1. Process Overview ───────────────────────────────────────────────────
    story.append(Paragraph("1. Process Discovery Assessment — Overview", st["section"]))
    assess_date = step1.get("assessment_date", "—")
    if assess_date and len(str(assess_date)) == 10 and str(assess_date)[4] == "-":
        y, mo, d = str(assess_date).split("-")
        assess_date = f"{d}-{mo}-{y}"

    overview_rows = [
        ["Field", "Value"],
        ["Process Name", step2.get("process_name") or report_fields.get("sub_process_name")],
        ["Business Function", step1.get("business_function")],
        ["Process Area", step1.get("process_area") or report_fields.get("process_area")],
        ["Assessment Date", assess_date],
        ["Currency", currency],
        ["Process Frequency", step2.get("process_frequency")],
        ["Data Quality", step2.get("quality_of_data") or report_fields.get("data_readiness")],
        ["Process SME", step1.get("sme_name")],
        ["Assessment Owner", step1.get("owner_name")],
        ["Status", str(p.get("status", "—")).replace("_", " ").title()],
    ]
    story.append(_make_table(overview_rows, [2.0 * inch, CONTENT_W - 2.0 * inch]))
    story.append(Spacer(1, 10))

    if step2.get("process_description"):
        story.append(Paragraph("Process Description", st["section"]))
        story.append(_para(step2["process_description"], st["body"]))
        story.append(Spacer(1, 8))

    goals = [g for g in (step2.get("goals") or []) if g and str(g).strip()]
    if goals:
        story.append(Paragraph("Goals / Outcomes", st["section"]))
        for i, g in enumerate(goals, 1):
            story.append(_para(f"{i}. {g}", st["body"]))
        story.append(Spacer(1, 8))

    # ── 3. Volumetrics & KPIs ─────────────────────────────────────────────────
    story.append(Paragraph("3. Volumetrics & KPIs", st["section"]))
    vol_unit = step3.get("transaction_volume_unit") or "units"
    time_unit = step3.get("processing_time_unit") or "minutes"

    vol_rows = [
        ["Metric", "Value"],
        ["Monthly Transaction Volume", _num(step3.get("monthly_transaction_volume"), vol_unit)],
        ["Processing Time (per transaction)", _num(step3.get("avg_time_per_transaction_mins"), time_unit)],
        ["FTE Count", _num(step3.get("fte_count"), "FTEs")],
        ["FTE Cost (Annual)", _money(step3.get("fte_cost_annual"), currency)],
        ["Cost Per Transaction", _money(step3.get("cost_per_transaction"), currency)],
        ["Hours Spent Per Day", _num(step3.get("hours_spent_per_day"), "hrs")],
        ["Working Days / Month", _num(step3.get("working_days_per_month"), "days")],
        ["Current Error Rate", _num(step3.get("current_error_rate_pct"), "%")],
        ["Business Impact of Errors (monthly)", _money(step3.get("business_impact_errors_monthly"), currency)],
        ["Revenue Leakage (Annual)", _money(step3.get("revenue_leakage"), currency)],
        ["SLA Breach Rate", _num(step3.get("sla_breach_rate_pct"), "%")],
        ["Non-Prime Transactions / Month", _num(step3.get("non_prime_transactions_monthly"), "txn")],
        ["Financial Risk (per transaction)", _money(step3.get("avg_financial_risk_per_txn"), currency)],
        ["Annual Cost Estimate", _money(step3.get("annual_cost_estimate"), currency)],
    ]
    story.append(_make_table(vol_rows, [2.8 * inch, CONTENT_W - 2.8 * inch]))
    obs = step3.get("process_observations") or step3.get("key_improvement_areas")
    if obs:
        story.append(Spacer(1, 6))
        story.append(Paragraph("Process Observations", ParagraphStyle(
            "obs_h", fontSize=9, fontName="Helvetica-Bold", textColor=BLUE, spaceAfter=3,
        )))
        story.append(_para(obs, st["body"]))
    story.append(Spacer(1, 10))

    # ── 4. GSDA ───────────────────────────────────────────────────────────────
    if step5:
        story.append(Paragraph("4. GSDA Evaluation", st["section"]))
        gsda_rows = [
            ["Dimension", "Score (out of 5)"],
            ["Standardization", str(step5.get("standardization", "—"))],
            ["Digitization", str(step5.get("digitization", "—"))],
            ["Data Availability", str(step5.get("data_availability", "—"))],
            ["Automation Feasibility", str(step5.get("automation_feasibility", "—"))],
            ["Overall GSDA Score", str(overall_gsda)],
        ]
        story.append(_make_table(gsda_rows, [2.8 * inch, CONTENT_W - 2.8 * inch]))
        if step5.get("ai_opportunity"):
            story.append(Spacer(1, 6))
            story.append(_para(f"AI Opportunity: {step5['ai_opportunity']}", st["body"]))
        story.append(Spacer(1, 10))

    # ── 5. Archetypes (brief) ─────────────────────────────────────────────────
    if selected_archetypes:
        story.append(Paragraph("5. Selected AI Archetypes", st["section"]))
        for arch in selected_archetypes:
            story.append(_para(
                f"{arch.get('archetype_name', '')} ({arch.get('fit_score', 0)}% fit) — "
                f"{arch.get('description', '')}",
                st["body"],
            ))
        story.append(Spacer(1, 8))

    # ── 6. Evaluation summary fields ──────────────────────────────────────────
    story.append(Paragraph("6. Evaluation Summary Report", st["section"]))
    field_labels = [
        ("process_area", "Process Area"),
        ("sub_process_name", "Sub-Process Name"),
        ("objective", "Objective"),
        ("strategic_goal", "Strategic Goal"),
        ("key_challenges", "Key Challenges"),
        ("business_benefits", "Business Benefits (Y1)"),
        ("ai_opportunity", "AI Opportunity"),
        ("data_readiness", "Data Readiness"),
        ("volume_capacity", "Volume and Capacity"),
        ("key_inputs", "Key Inputs"),
        ("key_outputs", "Key Outputs"),
    ]
    eval_rows = [["Field", "Details"]]
    for key, label in field_labels:
        val = report_fields.get(key) or step7.get(key)
        if not val and key == "sub_process_name":
            val = step2.get("process_name")
        if not val and key == "process_area":
            val = step1.get("process_area")
        if not val and key == "ai_opportunity":
            val = step5.get("ai_opportunity")
        eval_rows.append([label, val or "—"])
    story.append(_make_table(eval_rows, [2.2 * inch, CONTENT_W - 2.2 * inch]))
    story.append(Spacer(1, 10))

    # ── 7. Payback analysis ─────────────────────────────────────────────────────
    payback = step7.get("payback") or {}
    pb = _payback_metrics(step3, step5, payback)
    story.append(Paragraph("7. Payback Analysis", st["section"]))
    payback_rows = [
        ["Metric", "Value"],
        ["Implementation Cost", _money(pb["implementation_cost"], currency)],
        ["Annual Benefit", _money(pb["annual_benefit"], currency)],
        [
            "Payback Period",
            _num(pb["payback_period_months"], "months")
            if pb.get("payback_period_months") is not None
            else "—",
        ],
    ]
    story.append(_make_table(payback_rows, [2.4 * inch, CONTENT_W - 2.4 * inch]))
    story.append(Spacer(1, 10))

    # ── 8. Executive summary ──────────────────────────────────────────────────
    if step7.get("summary") or step7.get("next_steps"):
        story.append(Paragraph("8. Executive Summary", st["section"]))
        if step7.get("summary"):
            story.append(_para(step7["summary"], st["body"]))
        if step7.get("next_steps"):
            story.append(Spacer(1, 6))
            story.append(Paragraph("Recommended Next Steps", ParagraphStyle(
                "ns", fontSize=10, fontName="Helvetica-Bold", textColor=BLUE, spaceAfter=4,
            )))
            for i, s in enumerate(step7["next_steps"], 1):
                story.append(_para(f"{i}. {s}", st["body"]))
        story.append(Spacer(1, 10))

    # ── 9. Activity Breakdown (L3) ────────────────────────────────────────────
    activities = step4.get("activities", [])
    if activities:
        story.append(PageBreak())
        story.append(Paragraph("9. Activity Breakdown (L3)", st["section"]))
        story.append(Spacer(1, 4))

        act_rows = [[
            "Activity Name",
            "Description",
            "Data Management",
            "Source System",
            "Automation Level",
        ]]
        for a in activities:
            desc = a.get("description") or a.get("data_needed") or ""
            data_mgmt = a.get("data_management") or ""
            source = a.get("source_system") or a.get("integration_readiness") or ""
            auto = (
                a.get("existing_automation_level")
                or a.get("ai_automation_potential")
                or ""
            )
            act_rows.append([
                a.get("activity_name") or "—",
                desc,
                data_mgmt,
                source,
                auto,
            ])

        col_w = [
            1.15 * inch,
            2.05 * inch,
            1.35 * inch,
            1.05 * inch,
            0.95 * inch,
        ]
        story.append(_make_table(act_rows, col_w))

    doc.build(story, canvasmaker=_NumberedCanvas)
    buffer.seek(0)

    safe_name = (step2.get("process_name") or "Report").replace(" ", "_")[:40]
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="AuRA_{safe_name}_{process_id[:8]}.pdf"'
        },
    )
